apiVersion: v1
kind: Secret
metadata:
  name: ingress-secret-tls
  namespace: ingress-test
type: kubernetes.io/tls
data:
  tls.crt: |
    < cat ingress-tls.crt | base64 >
  tls.key: |
    < cat ingress-tls.key | base64 >